# Generated by Django 4.2.6 on 2023-10-18 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("a", models.CharField(max_length=200)),
                ("b", models.CharField(max_length=200)),
                ("c", models.CharField(max_length=200)),
                (
                    "correct_answer",
                    models.CharField(
                        choices=[
                            ("a", "Answer A"),
                            ("b", "Answer B"),
                            ("c", "Answer C"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                (
                    "answers",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.answers"
                    ),
                ),
            ],
        ),
    ]
